title: "Sanic-JWT-Extended"
description: >- # this means to ignore newlines until "baseurl:"
  ðŸ›¡An open source Sanic extension that provides JWT support ðŸ›¡
github_username: NovemberOscar

theme: "just-the-docs"

heading_anchors: true
search_enabled: true
search_tokenizer_separator: /[\s/]+/
aux_links:
  "Sanic-JWT-Extended on Github":
    - "//github.com/NovemberOscar/Sanic-JWT-Extended"
footer_content: 'Copyright &copy; 2017-2019 Seonghyeon Kim. Distributed by an <a href="https://github.com/NovemberOscar/Sanic-JWT-Extended/tree/master/LICENSE">MIT license.</a>'

repository: NovemberOscar/Sanic-JWT-Extended

plugins:
  - "jekyll-github-metadata"
  - jekyll-seo-tag

ga_tracking: UA-143368612-3
